---
title: "Untitled"
author: "Rachael RAY Hobbs"
date: "2026-02-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


Load libraries for association rule mining
```{r}
library(arules)
library(arulesViz)
library(arulesCBA)
library(tidyverse)
resumes <- read.csv("resume_data.csv") #kaggle
```


Subset data and bin matching score
```{r}
head(resumes)
resumes_short <- resumes %>%
  select(c("skills", "major_field_of_studies", "related_skils_in_job", "positions", "responsibilities", "X.job_position_name", "extra_curricular_activity_types", "certification_skills", "matched_score")) %>%
filter(X.job_position_name %in% c(
  "Senior Software Engineer",
  "Machine Learning (ML) Engineer",
  "Senior iOS Engineer",
  "AI Engineer",
  "Database Administrator (DBA)",
  "Network Support Engineer",
  "DevOps Engineer",
  "Data Engineer",
  "Full Stack Developer (Python,React js)",
  "Data Science Engineer"
)) %>%
  mutate(
  score_bin = discretize(matched_score, method="interval", breaks=10)
  )
```


Skills with high lift
```{r}
# Keep only needed columns
resumes_skills <- resumes_short %>%
  select(skills, score_bin)

# Split skills
skills_list <- strsplit(resumes_skills$skills, ",")

# Combine skills + score bin per resume
word_list <- Map(
  function(skill_vec, sb) {
    items <- c(skill_vec, paste0("score_bin=", sb))
    items <- trimws(items)
    unique(items[nzchar(items)])
  },
  skills_list,
  resumes_skills$score_bin
)

# Convert to transactions
trans <- as(word_list, "transactions")
```


```{r}
bins <- unique(paste0("score_bin=", resumes_skills$score_bin))

rhs_item <- names(sort(itemFrequency(trans)[bins], decreasing = TRUE))[1:2]

rules <- apriori(
  trans,
  parameter = list(sup = 0.005, conf = 0.60, minlen = 2),
  appearance = list(default = "lhs", rhs = rhs_item),
  control = list(verbose = FALSE)
)

length(rules)
inspect(head(sort(rules, by="support"), 20))
```

```{r}
rules_f <- subset(rules, subset = lift < 1)
inspect(head(sort(rules_f, by="lift", decreasing=FALSE), 5))
```


Job skills with high lift
```{r}
# Keep only needed columns
resumes_job_skills <- resumes_short %>%
  select(related_skils_in_job, score_bin)


# Split skills
skills_list <- strsplit(resumes_job_skills$related_skils_in_job, ",")

# Combine skills + score bin per resume
word_list <- Map(
  function(skill_vec, sb) {
    items <- c(skill_vec, paste0("score_bin=", sb))
    items <- trimws(items)
    unique(items[nzchar(items)])
  },
  skills_list,
  resumes_job_skills$score_bin
)

# Convert to transactions
trans <- as(word_list, "transactions")
```



```{r}
bins <- unique(paste0("score_bin=", resumes_job_skills$score_bin))

rhs_item <- names(sort(itemFrequency(trans)[bins], decreasing = TRUE))[1:2]

rules <- apriori(
  trans,
  parameter = list(sup = 0.005, conf = 0.60, minlen = 2),
  appearance = list(default = "lhs", rhs = rhs_item),
  control = list(verbose = FALSE)
)

length(rules)
inspect(head(rules, 20))
```

```{r}
rules_f <- subset(rules, subset = lift < 1)
inspect(head(sort(rules_f, by="lift", decreasing=FALSE), 5))
```

Responsibilities with high lift
```{r}
# Keep only needed columns
resumes_responsibilities <- resumes_short %>%
  select(responsibilities, score_bin)


# Split skills
skills_list <- strsplit(resumes_responsibilities$responsibilities, " ")

# Combine skills + score bin per resume
word_list <- Map(
  function(skill_vec, sb) {
    items <- c(skill_vec, paste0("score_bin=", sb))
    items <- trimws(items)
    unique(items[nzchar(items)])
  },
  skills_list,
  resumes_responsibilities$score_bin
)

# Convert to transactions
trans <- as(word_list, "transactions")

```



```{r}
bins <- unique(paste0("score_bin=", resumes_responsibilities$score_bin))

rhs_item <- names(sort(itemFrequency(trans)[bins], decreasing = TRUE))[1:2]

rules <- apriori(
  trans,
  parameter = list(sup = 0.001, conf = 0.20, minlen = 2),
  appearance = list(default = "lhs", rhs = rhs_item),
  control = list(verbose = FALSE)
)

length(rules)
inspect(head(rules, 20))
```

```{r}
rules_f <- subset(rules, subset = lift < 1)
inspect(head(sort(rules_f, by="lift", decreasing=FALSE), 5))
```


Major field of studies with highest lift
```{r}
# Keep only needed columns
resumes_field <- resumes_short %>%
  select(major_field_of_studies, score_bin)


# Split skills
skills_list <- strsplit(resumes_field$major_field_of_studies, ",")

# Combine skills + score bin per resume
word_list <- Map(
  function(skill_vec, sb) {
    items <- c(skill_vec, paste0("score_bin=", sb))
    items <- trimws(items)
    unique(items[nzchar(items)])
  },
  skills_list,
  resumes_field$score_bin
)

# Convert to transactions
trans <- as(word_list, "transactions")

```



```{r}
bins <- unique(paste0("score_bin=", resumes_field$score_bin))

rhs_item <- names(sort(itemFrequency(trans)[bins], decreasing = TRUE))[1:2]

rules <- apriori(
  trans,
  parameter = list(sup = 0.001, conf = 0.60, minlen = 2),
  appearance = list(default = "lhs", rhs = rhs_item),
  control = list(verbose = FALSE)
)

length(rules)
inspect(head(rules, 20))
```

```{r}
rules_f <- subset(rules, subset = lift < 1)
inspect(head(sort(rules_f, by="lift", decreasing=FALSE), 5))
```

Previous positions with high lift
```{r}
# Keep only needed columns
resumes_positions <- resumes_short %>%
  select(positions, score_bin)


# Split skills
skills_list <- strsplit(resumes_positions$positions, ",")

# Combine skills + score bin per resume
word_list <- Map(
  function(skill_vec, sb) {
    items <- c(skill_vec, paste0("score_bin=", sb))
    items <- trimws(items)
    unique(items[nzchar(items)])
  },
  skills_list,
  resumes_positions$score_bin
)

# Convert to transactions
trans <- as(word_list, "transactions")

```



```{r}
bins <- unique(paste0("score_bin=", resumes_positions$score_bin))

rhs_item <- names(sort(itemFrequency(trans)[bins], decreasing = TRUE))[1:2]

rules <- apriori(
  trans,
  parameter = list(sup = 0.005, conf = 0.60, minlen = 2),
  appearance = list(default = "lhs", rhs = rhs_item),
  control = list(verbose = FALSE)
)

length(rules)
inspect(head(rules, 20))
```

```{r}
rules_f <- subset(rules, subset = lift < 1)
inspect(head(sort(rules_f, by="lift", decreasing=FALSE), 5))
```




